//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MARC.HI.EHRS.SVC.Terminology.CTSService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageRuntimeSoap", Namespace="urn://hl7.org/CTSMAPI")]
    public partial class MessageRuntime : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCTSVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHL7ReleaseVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateTranslationOperationCompleted;
        
        private System.Threading.SendOrPostCallback fillInDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback areEquivalentOperationCompleted;
        
        private System.Threading.SendOrPostCallback subsumesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSupportedMatchAlgoritmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSupportedVocabularyDomainsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageRuntime() {
            this.Url = global::MARC.HI.EHRS.SVC.Terminology.Properties.Settings.Default.MARC_HI_EHRS_SVC_Terminology_MessageRuntime_MessageRuntime;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCTSVersionCompletedEventHandler getCTSVersionCompleted;
        
        /// <remarks/>
        public event getServiceNameCompletedEventHandler getServiceNameCompleted;
        
        /// <remarks/>
        public event getServiceDescriptionCompletedEventHandler getServiceDescriptionCompleted;
        
        /// <remarks/>
        public event getServiceVersionCompletedEventHandler getServiceVersionCompleted;
        
        /// <remarks/>
        public event validateCodeCompletedEventHandler validateCodeCompleted;
        
        /// <remarks/>
        public event getHL7ReleaseVersionCompletedEventHandler getHL7ReleaseVersionCompleted;
        
        /// <remarks/>
        public event translateCodeCompletedEventHandler translateCodeCompleted;
        
        /// <remarks/>
        public event validateTranslationCompletedEventHandler validateTranslationCompleted;
        
        /// <remarks/>
        public event fillInDetailsCompletedEventHandler fillInDetailsCompleted;
        
        /// <remarks/>
        public event areEquivalentCompletedEventHandler areEquivalentCompleted;
        
        /// <remarks/>
        public event subsumesCompletedEventHandler subsumesCompleted;
        
        /// <remarks/>
        public event getSupportedMatchAlgoritmsCompletedEventHandler getSupportedMatchAlgoritmsCompleted;
        
        /// <remarks/>
        public event getSupportedVocabularyDomainsCompletedEventHandler getSupportedVocabularyDomainsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getCTSVersion", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getCTSVersionReturn")]
        public CTSVersionId getCTSVersion() {
            object[] results = this.Invoke("getCTSVersion", new object[0]);
            return ((CTSVersionId)(results[0]));
        }
        
        /// <remarks/>
        public void getCTSVersionAsync() {
            this.getCTSVersionAsync(null);
        }
        
        /// <remarks/>
        public void getCTSVersionAsync(object userState) {
            if ((this.getCTSVersionOperationCompleted == null)) {
                this.getCTSVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCTSVersionOperationCompleted);
            }
            this.InvokeAsync("getCTSVersion", new object[0], this.getCTSVersionOperationCompleted, userState);
        }
        
        private void OngetCTSVersionOperationCompleted(object arg) {
            if ((this.getCTSVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCTSVersionCompleted(this, new getCTSVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getServiceName", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getServiceNameReturn")]
        public ST getServiceName() {
            object[] results = this.Invoke("getServiceName", new object[0]);
            return ((ST)(results[0]));
        }
        
        /// <remarks/>
        public void getServiceNameAsync() {
            this.getServiceNameAsync(null);
        }
        
        /// <remarks/>
        public void getServiceNameAsync(object userState) {
            if ((this.getServiceNameOperationCompleted == null)) {
                this.getServiceNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceNameOperationCompleted);
            }
            this.InvokeAsync("getServiceName", new object[0], this.getServiceNameOperationCompleted, userState);
        }
        
        private void OngetServiceNameOperationCompleted(object arg) {
            if ((this.getServiceNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceNameCompleted(this, new getServiceNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getServiceDescription", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getServiceDescriptionReturn")]
        public ST getServiceDescription() {
            object[] results = this.Invoke("getServiceDescription", new object[0]);
            return ((ST)(results[0]));
        }
        
        /// <remarks/>
        public void getServiceDescriptionAsync() {
            this.getServiceDescriptionAsync(null);
        }
        
        /// <remarks/>
        public void getServiceDescriptionAsync(object userState) {
            if ((this.getServiceDescriptionOperationCompleted == null)) {
                this.getServiceDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceDescriptionOperationCompleted);
            }
            this.InvokeAsync("getServiceDescription", new object[0], this.getServiceDescriptionOperationCompleted, userState);
        }
        
        private void OngetServiceDescriptionOperationCompleted(object arg) {
            if ((this.getServiceDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceDescriptionCompleted(this, new getServiceDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getServiceVersion", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getServiceVersionReturn")]
        public ST getServiceVersion() {
            object[] results = this.Invoke("getServiceVersion", new object[0]);
            return ((ST)(results[0]));
        }
        
        /// <remarks/>
        public void getServiceVersionAsync() {
            this.getServiceVersionAsync(null);
        }
        
        /// <remarks/>
        public void getServiceVersionAsync(object userState) {
            if ((this.getServiceVersionOperationCompleted == null)) {
                this.getServiceVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceVersionOperationCompleted);
            }
            this.InvokeAsync("getServiceVersion", new object[0], this.getServiceVersionOperationCompleted, userState);
        }
        
        private void OngetServiceVersionOperationCompleted(object arg) {
            if ((this.getServiceVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceVersionCompleted(this, new getServiceVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("validateCode", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("validateCodeReturn")]
        public ValidateCodeReturn validateCode(ST vocabularyDomain_name, CD codeToValidate, ST applicationContext_code, BL activeConceptsOnly, BL errorCheckOnly) {
            object[] results = this.Invoke("validateCode", new object[] {
                        vocabularyDomain_name,
                        codeToValidate,
                        applicationContext_code,
                        activeConceptsOnly,
                        errorCheckOnly});
            return ((ValidateCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void validateCodeAsync(ST vocabularyDomain_name, CD codeToValidate, ST applicationContext_code, BL activeConceptsOnly, BL errorCheckOnly) {
            this.validateCodeAsync(vocabularyDomain_name, codeToValidate, applicationContext_code, activeConceptsOnly, errorCheckOnly, null);
        }
        
        /// <remarks/>
        public void validateCodeAsync(ST vocabularyDomain_name, CD codeToValidate, ST applicationContext_code, BL activeConceptsOnly, BL errorCheckOnly, object userState) {
            if ((this.validateCodeOperationCompleted == null)) {
                this.validateCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateCodeOperationCompleted);
            }
            this.InvokeAsync("validateCode", new object[] {
                        vocabularyDomain_name,
                        codeToValidate,
                        applicationContext_code,
                        activeConceptsOnly,
                        errorCheckOnly}, this.validateCodeOperationCompleted, userState);
        }
        
        private void OnvalidateCodeOperationCompleted(object arg) {
            if ((this.validateCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateCodeCompleted(this, new validateCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getHL7ReleaseVersion", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getHL7ReleaseVersionReturn")]
        public ST getHL7ReleaseVersion() {
            object[] results = this.Invoke("getHL7ReleaseVersion", new object[0]);
            return ((ST)(results[0]));
        }
        
        /// <remarks/>
        public void getHL7ReleaseVersionAsync() {
            this.getHL7ReleaseVersionAsync(null);
        }
        
        /// <remarks/>
        public void getHL7ReleaseVersionAsync(object userState) {
            if ((this.getHL7ReleaseVersionOperationCompleted == null)) {
                this.getHL7ReleaseVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHL7ReleaseVersionOperationCompleted);
            }
            this.InvokeAsync("getHL7ReleaseVersion", new object[0], this.getHL7ReleaseVersionOperationCompleted, userState);
        }
        
        private void OngetHL7ReleaseVersionOperationCompleted(object arg) {
            if ((this.getHL7ReleaseVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHL7ReleaseVersionCompleted(this, new getHL7ReleaseVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("translateCode", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("translateCodeReturn")]
        public CD translateCode(ST vocabularyDomainName, CD fromCode, UID toCodeSystemId, ST applicationContextCode) {
            object[] results = this.Invoke("translateCode", new object[] {
                        vocabularyDomainName,
                        fromCode,
                        toCodeSystemId,
                        applicationContextCode});
            return ((CD)(results[0]));
        }
        
        /// <remarks/>
        public void translateCodeAsync(ST vocabularyDomainName, CD fromCode, UID toCodeSystemId, ST applicationContextCode) {
            this.translateCodeAsync(vocabularyDomainName, fromCode, toCodeSystemId, applicationContextCode, null);
        }
        
        /// <remarks/>
        public void translateCodeAsync(ST vocabularyDomainName, CD fromCode, UID toCodeSystemId, ST applicationContextCode, object userState) {
            if ((this.translateCodeOperationCompleted == null)) {
                this.translateCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateCodeOperationCompleted);
            }
            this.InvokeAsync("translateCode", new object[] {
                        vocabularyDomainName,
                        fromCode,
                        toCodeSystemId,
                        applicationContextCode}, this.translateCodeOperationCompleted, userState);
        }
        
        private void OntranslateCodeOperationCompleted(object arg) {
            if ((this.translateCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateCodeCompleted(this, new translateCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("validateTranslation", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("validateTranslationReturn")]
        public ValidateCodeReturn validateTranslation(ST vocabularyDomain_name, CD codeToValidate, ST applicationContext_code, BL activeConceptsOnly, BL errorCheckOnly) {
            object[] results = this.Invoke("validateTranslation", new object[] {
                        vocabularyDomain_name,
                        codeToValidate,
                        applicationContext_code,
                        activeConceptsOnly,
                        errorCheckOnly});
            return ((ValidateCodeReturn)(results[0]));
        }
        
        /// <remarks/>
        public void validateTranslationAsync(ST vocabularyDomain_name, CD codeToValidate, ST applicationContext_code, BL activeConceptsOnly, BL errorCheckOnly) {
            this.validateTranslationAsync(vocabularyDomain_name, codeToValidate, applicationContext_code, activeConceptsOnly, errorCheckOnly, null);
        }
        
        /// <remarks/>
        public void validateTranslationAsync(ST vocabularyDomain_name, CD codeToValidate, ST applicationContext_code, BL activeConceptsOnly, BL errorCheckOnly, object userState) {
            if ((this.validateTranslationOperationCompleted == null)) {
                this.validateTranslationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateTranslationOperationCompleted);
            }
            this.InvokeAsync("validateTranslation", new object[] {
                        vocabularyDomain_name,
                        codeToValidate,
                        applicationContext_code,
                        activeConceptsOnly,
                        errorCheckOnly}, this.validateTranslationOperationCompleted, userState);
        }
        
        private void OnvalidateTranslationOperationCompleted(object arg) {
            if ((this.validateTranslationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateTranslationCompleted(this, new validateTranslationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("fillInDetails", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("fillInDetailsReturn")]
        public CD fillInDetails(CD codeToFillIn, ST displayLanguage_code) {
            object[] results = this.Invoke("fillInDetails", new object[] {
                        codeToFillIn,
                        displayLanguage_code});
            return ((CD)(results[0]));
        }
        
        /// <remarks/>
        public void fillInDetailsAsync(CD codeToFillIn, ST displayLanguage_code) {
            this.fillInDetailsAsync(codeToFillIn, displayLanguage_code, null);
        }
        
        /// <remarks/>
        public void fillInDetailsAsync(CD codeToFillIn, ST displayLanguage_code, object userState) {
            if ((this.fillInDetailsOperationCompleted == null)) {
                this.fillInDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfillInDetailsOperationCompleted);
            }
            this.InvokeAsync("fillInDetails", new object[] {
                        codeToFillIn,
                        displayLanguage_code}, this.fillInDetailsOperationCompleted, userState);
        }
        
        private void OnfillInDetailsOperationCompleted(object arg) {
            if ((this.fillInDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fillInDetailsCompleted(this, new fillInDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("areEquivalent", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("areEquivalentReturn")]
        public BL areEquivalent(CD code1, CD code2) {
            object[] results = this.Invoke("areEquivalent", new object[] {
                        code1,
                        code2});
            return ((BL)(results[0]));
        }
        
        /// <remarks/>
        public void areEquivalentAsync(CD code1, CD code2) {
            this.areEquivalentAsync(code1, code2, null);
        }
        
        /// <remarks/>
        public void areEquivalentAsync(CD code1, CD code2, object userState) {
            if ((this.areEquivalentOperationCompleted == null)) {
                this.areEquivalentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnareEquivalentOperationCompleted);
            }
            this.InvokeAsync("areEquivalent", new object[] {
                        code1,
                        code2}, this.areEquivalentOperationCompleted, userState);
        }
        
        private void OnareEquivalentOperationCompleted(object arg) {
            if ((this.areEquivalentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.areEquivalentCompleted(this, new areEquivalentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("subsumes", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("subsumesReturn")]
        public BL subsumes(CD parentCode, CD childCode) {
            object[] results = this.Invoke("subsumes", new object[] {
                        parentCode,
                        childCode});
            return ((BL)(results[0]));
        }
        
        /// <remarks/>
        public void subsumesAsync(CD parentCode, CD childCode) {
            this.subsumesAsync(parentCode, childCode, null);
        }
        
        /// <remarks/>
        public void subsumesAsync(CD parentCode, CD childCode, object userState) {
            if ((this.subsumesOperationCompleted == null)) {
                this.subsumesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubsumesOperationCompleted);
            }
            this.InvokeAsync("subsumes", new object[] {
                        parentCode,
                        childCode}, this.subsumesOperationCompleted, userState);
        }
        
        private void OnsubsumesOperationCompleted(object arg) {
            if ((this.subsumesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.subsumesCompleted(this, new subsumesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getSupportedMatchAlgorithms", RequestElementName="getSupportedMatchAlgorithms", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseElementName="getSupportedMatchAlgorithmsResponse", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getSupportedMatchAlgorithmsReturn")]
        public ST[] getSupportedMatchAlgoritms() {
            object[] results = this.Invoke("getSupportedMatchAlgoritms", new object[0]);
            return ((ST[])(results[0]));
        }
        
        /// <remarks/>
        public void getSupportedMatchAlgoritmsAsync() {
            this.getSupportedMatchAlgoritmsAsync(null);
        }
        
        /// <remarks/>
        public void getSupportedMatchAlgoritmsAsync(object userState) {
            if ((this.getSupportedMatchAlgoritmsOperationCompleted == null)) {
                this.getSupportedMatchAlgoritmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSupportedMatchAlgoritmsOperationCompleted);
            }
            this.InvokeAsync("getSupportedMatchAlgoritms", new object[0], this.getSupportedMatchAlgoritmsOperationCompleted, userState);
        }
        
        private void OngetSupportedMatchAlgoritmsOperationCompleted(object arg) {
            if ((this.getSupportedMatchAlgoritmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSupportedMatchAlgoritmsCompleted(this, new getSupportedMatchAlgoritmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getSupportedVocabularyDomains", RequestNamespace="urn://hl7.org/CTSMAPI", ResponseNamespace="urn://hl7.org/CTSMAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getSupportedVocabularyDomainsReturn")]
        public ST[] getSupportedVocabularyDomains(ST matchText, ST matchAlgorithm_code, long timeout, long sizeLimit) {
            object[] results = this.Invoke("getSupportedVocabularyDomains", new object[] {
                        matchText,
                        matchAlgorithm_code,
                        timeout,
                        sizeLimit});
            return ((ST[])(results[0]));
        }
        
        /// <remarks/>
        public void getSupportedVocabularyDomainsAsync(ST matchText, ST matchAlgorithm_code, long timeout, long sizeLimit) {
            this.getSupportedVocabularyDomainsAsync(matchText, matchAlgorithm_code, timeout, sizeLimit, null);
        }
        
        /// <remarks/>
        public void getSupportedVocabularyDomainsAsync(ST matchText, ST matchAlgorithm_code, long timeout, long sizeLimit, object userState) {
            if ((this.getSupportedVocabularyDomainsOperationCompleted == null)) {
                this.getSupportedVocabularyDomainsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSupportedVocabularyDomainsOperationCompleted);
            }
            this.InvokeAsync("getSupportedVocabularyDomains", new object[] {
                        matchText,
                        matchAlgorithm_code,
                        timeout,
                        sizeLimit}, this.getSupportedVocabularyDomainsOperationCompleted, userState);
        }
        
        private void OngetSupportedVocabularyDomainsOperationCompleted(object arg) {
            if ((this.getSupportedVocabularyDomainsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSupportedVocabularyDomainsCompleted(this, new getSupportedVocabularyDomainsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://hl7.org/CTSMAPI")]
    public partial class CTSVersionId {
        
        private INT majorField;
        
        private INT minorField;
        
        /// <remarks/>
        public INT major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public INT minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class INT {
        
        private int vField;
        
        /// <remarks/>
        public int v {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class UID {
        
        private string vField;
        
        /// <remarks/>
        public string v {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class CV {
        
        private string codeField;
        
        private ED originalTextField;
        
        private CS codingRationaleField;
        
        private string codeSystemField;
        
        private string codeSystemNameField;
        
        private string codeSystemVersionField;
        
        private string displayNameField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public ED originalText {
            get {
                return this.originalTextField;
            }
            set {
                this.originalTextField = value;
            }
        }
        
        /// <remarks/>
        public CS codingRationale {
            get {
                return this.codingRationaleField;
            }
            set {
                this.codingRationaleField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystem {
            get {
                return this.codeSystemField;
            }
            set {
                this.codeSystemField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemName {
            get {
                return this.codeSystemNameField;
            }
            set {
                this.codeSystemNameField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemVersion {
            get {
                return this.codeSystemVersionField;
            }
            set {
                this.codeSystemVersionField = value;
            }
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class ED {
        
        private binary_or_text _thisField;
        
        private string encodingField;
        
        private string mediaTypeField;
        
        private string compressionField;
        
        private byte[] integrityCheckField;
        
        private string referenceField;
        
        private string ingegrityCheckAlgorithmField;
        
        private string charsetField;
        
        private string languageField;
        
        private CD[] thumbnailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public binary_or_text _this {
            get {
                return this._thisField;
            }
            set {
                this._thisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string compression {
            get {
                return this.compressionField;
            }
            set {
                this.compressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] integrityCheck {
            get {
                return this.integrityCheckField;
            }
            set {
                this.integrityCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ingegrityCheckAlgorithm {
            get {
                return this.ingegrityCheckAlgorithmField;
            }
            set {
                this.ingegrityCheckAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="urn://hl7.org/CTSMAPI", IsNullable=false)]
        public CD[] thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class binary_or_text {
        
        private System.Xml.XmlNode[] itemTypeField;
        
        private byte[] binaryValueField;
        
        private string textualValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemType")]
        public System.Xml.XmlNode[] itemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] binaryValue {
            get {
                return this.binaryValueField;
            }
            set {
                this.binaryValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string textualValue {
            get {
                return this.textualValueField;
            }
            set {
                this.textualValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class CD {
        
        private CD[] translationField;
        
        private CD[] qualifiersField;
        
        private string codeField;
        
        private ED originalTextField;
        
        private CS codingRationaleField;
        
        private string codeSystemField;
        
        private string codeSystemNameField;
        
        private string codeSystemVersionField;
        
        private string displayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="urn://hl7.org/CTSMAPI", IsNullable=false)]
        public CD[] translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="urn://hl7.org/CTSMAPI", IsNullable=false)]
        public CD[] qualifiers {
            get {
                return this.qualifiersField;
            }
            set {
                this.qualifiersField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public ED originalText {
            get {
                return this.originalTextField;
            }
            set {
                this.originalTextField = value;
            }
        }
        
        /// <remarks/>
        public CS codingRationale {
            get {
                return this.codingRationaleField;
            }
            set {
                this.codingRationaleField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystem {
            get {
                return this.codeSystemField;
            }
            set {
                this.codeSystemField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemName {
            get {
                return this.codeSystemNameField;
            }
            set {
                this.codeSystemNameField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemVersion {
            get {
                return this.codeSystemVersionField;
            }
            set {
                this.codeSystemVersionField = value;
            }
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class CS {
        
        private string codeField;
        
        private ED originalTextField;
        
        private CS codingRationaleField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public ED originalText {
            get {
                return this.originalTextField;
            }
            set {
                this.originalTextField = value;
            }
        }
        
        /// <remarks/>
        public CS codingRationale {
            get {
                return this.codingRationaleField;
            }
            set {
                this.codingRationaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://hl7.org/CTSMAPI")]
    public partial class ValidationDetail {
        
        private CV codeInErrorField;
        
        private BL isErrorField;
        
        private ST error_idField;
        
        private ST errorTextField;
        
        /// <remarks/>
        public CV codeInError {
            get {
                return this.codeInErrorField;
            }
            set {
                this.codeInErrorField = value;
            }
        }
        
        /// <remarks/>
        public BL isError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public ST error_id {
            get {
                return this.error_idField;
            }
            set {
                this.error_idField = value;
            }
        }
        
        /// <remarks/>
        public ST errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class BL {
        
        private bool vField;
        
        /// <remarks/>
        public bool v {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://cts.hl7.org/types")]
    public partial class ST {
        
        private string vField;
        
        /// <remarks/>
        public string v {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://hl7.org/CTSMAPI")]
    public partial class ValidateCodeReturn {
        
        private INT nErrorsField;
        
        private INT nWarningsField;
        
        private ValidationDetail[] detailField;
        
        /// <remarks/>
        public INT nErrors {
            get {
                return this.nErrorsField;
            }
            set {
                this.nErrorsField = value;
            }
        }
        
        /// <remarks/>
        public INT nWarnings {
            get {
                return this.nWarningsField;
            }
            set {
                this.nWarningsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public ValidationDetail[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getCTSVersionCompletedEventHandler(object sender, getCTSVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCTSVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCTSVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CTSVersionId Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CTSVersionId)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getServiceNameCompletedEventHandler(object sender, getServiceNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServiceNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getServiceDescriptionCompletedEventHandler(object sender, getServiceDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServiceDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getServiceVersionCompletedEventHandler(object sender, getServiceVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServiceVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void validateCodeCompletedEventHandler(object sender, validateCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidateCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidateCodeReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getHL7ReleaseVersionCompletedEventHandler(object sender, getHL7ReleaseVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHL7ReleaseVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHL7ReleaseVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void translateCodeCompletedEventHandler(object sender, translateCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CD Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CD)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void validateTranslationCompletedEventHandler(object sender, validateTranslationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateTranslationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateTranslationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidateCodeReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidateCodeReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void fillInDetailsCompletedEventHandler(object sender, fillInDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fillInDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fillInDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CD Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CD)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void areEquivalentCompletedEventHandler(object sender, areEquivalentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class areEquivalentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal areEquivalentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BL Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BL)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void subsumesCompletedEventHandler(object sender, subsumesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class subsumesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal subsumesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BL Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BL)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getSupportedMatchAlgoritmsCompletedEventHandler(object sender, getSupportedMatchAlgoritmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSupportedMatchAlgoritmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSupportedMatchAlgoritmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getSupportedVocabularyDomainsCompletedEventHandler(object sender, getSupportedVocabularyDomainsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSupportedVocabularyDomainsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSupportedVocabularyDomainsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591